package.json

This solves the following Webpack warnings when using `react` and `react-dom`'s more recent minor versions:
```
myproj@1.0.0
├── UNMET PEER DEPENDENCY react@0.14.7
├── UNMET PEER DEPENDENCY react-dom@0.14.7
└── react-plaid-link@0.1.0 
npm WARN react-plaid-link@0.1.0 requires a peer of react@0.14.0 but none was installed.
npm WARN react-plaid-link@0.1.0 requires a peer of react-dom@0.14.0 but none was installed.
```

Allow any react 0.14.x version in peerDeps

---

src/PlaidLink.js

After the component mounts the first time, the plaid script and iframe is injected into the DOM. This does not happen the second time the component mounts, but the component does not check the DOM for the existence of the Plaid object. Therefore `this.state.linkLoaded` remains false the component remounts. 
Set `linkHandler` inside the global `window` object. And instead of checking `this.state` for whether or not the link is ready, simply check that `window.linkHandler` exists.

fix a bug when unmounting component

---

src/PlaidLink.js

This fixes the error:
```
Uncaught TypeError: Cannot read property 'open' of undefined
at Constructor.handleOnClick (eval at evalScript (http://localhost:3000/_next/next-dev.bundle.js:35040:4), <anonymous>:18030:24)
```

fix: undefined method

---

src/PlaidLink.js

Hi, this is my first attempt to contribute to this repo. Please let me know if there is anything I need to do differently in the process. Hopefully, this proposed change is self explanatory. You may have noticed the recent console warning that longtail is deprecated for plaid link. It looks like it is no longer needed, so we should take it out of here as well.

Removing longtail, since it is now deprecated in Plaid Link

---

src/PlaidLink.js

Getting an error due to the fact that there are now 3 environments and `tartan` is not one of them:
```
link.js:125 Error: Invalid env: "tartan". env must be "sandbox", "development" or "production".
at error (link.js:337)
at link.js:337
at link.js:125
```
https://plaid.com/docs/api/

add sandbox and development to env prop options

---

README.md
package.json
src/PlaidLink.js

- Added prop to initialize Plaid Link with API V2 to solve this warning: 
```
link.js:1 A new version of Plaid API is available. Check out the transition guide at https://plaid.com/docs/link/transition-guide to get your integration updated. To get started quickly, initialize Link with the `apiVersion` flag set to `v2`.
warn	@	link.js:1
```
[https://plaid.com/docs/link/transition-guide/#client-side-integration](https://plaid.com/docs/link/transition-guide/#client-side-integration)
- Added prop-types library, because of React.PropTypes is deprecated and this solves the next warning: 
```
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead
```
[https://facebook.github.io/react/warnings/dont-call-proptypes.html](https://facebook.gi …

Some updates:

---

README.md

Longtail is no longer supported by Plaid Link

Remove longtail from docs

---

src/PlaidLink.js

This adds calling `this.props.onClick()` from the onClick handler so as to flexibly prevent form submissions or provide functionality as the Plaid window is opened.

Call this.props.onClick() from handleOnClick

---

.babelrc
.eslintrc.js
Makefile
package.json
src/PlaidLink.js

- Utilizes `extends Component`
- Changes load script library
- Moves `link-initialize.js` URL into state
- Wraps return elements in a `<div>`
Passing `make test` and working in a sample app we made as well. Hope this is a valuable contribution!

Update PlaidLink.js to ES6 format

---

src/PlaidLink.js

allows `assets` product to be included in the `products` prop.
[From the docs](https://plaid.com/docs/#integrating-with-link), `assets` is now an allowed product.
Screenshot from docs:

allow assets as product type

---

src/PlaidLink.js

It's useful in cases where the PlaidLink is inside a form and we need to do something like:
```
<PlaidLink onClick={e => e.preventDefault()}>...
```

Pass the click event down to the onClick function

---

README.md
src/PlaidLink.js

Adds support for the `oauthNonce`, `oauthRedirectUri`, and `oauthStateId` Link configuration parameters required for OAuth authentication flows when initializing Link with European country codes, as well as support for the Payment Initiation product.

Add support for OAuth and Payment Initiation

---

src/factory.ts

Hi! I started using `usePlaidLink` and noticed a `console.log` call.

Remove console log from factory.ts

---

.storybook/example.stories.js
examples/hoc.js
examples/hooks.js
src/factory.ts
src/types/index.ts
src/usePlaidLink.ts

- Allows public_key to be optional if a token is provided
- Recreates the link handler if the token is updated
- Use the new link handler `.destroy()` method instead of the one-off implementation here

Add support for link_tokens 

---

package.json

Use a version of `react-script-hook` with https://github.com/hupe1980/react-script-hook/pull/10 is merged.

Pull in fixed version of react-script-hook

---

package.json
yarn.lock

I only bumped package.json, not yarn.lock 🙈 
Shall we migrate over to `package-lock.json`? I doubt many people would think about yarn these days, so it's a bit of an elephant trap.

Bump yarn.lock

---

package.json
src/usePlaidLink.ts
yarn.lock

This fixes #107 by upgrading `react-script-hook` to 1.1.0 and using the `checkIfExisting` flag

Ensure Plaid link-initialize.js is embedded only once

---

src/types/index.ts
src/usePlaidLink.ts

- The clientName, env, and product should now be empty if also using a link_token.

update typescript types for optional configs

---

.storybook/example.legacy.stories.js
.storybook/main.js
README.md
examples/hoc.legacy.js
examples/hooks.legacy.js

Update the readme and examples to reflect that link_tokens is the new and preferred way of integrating with Plaid Link. We still have the public_key examples but they're labeled as "legacy".

update readme and examples

---

src/factory.ts

Fix for issue #133. We were not setting the external `open` state to reflect a manually exited Link pane, causing the `destroy` method to be skipped when the Link pane was closed and then force exit triggered.

Update open state onExit

---

CHANGELOG.md

- includes a fix for the usePlaidLink `ready` state.

update changelog for 3.1.1

---

CHANGELOG.md
Makefile
PUBLISH.md
README.md

1. Updates changelog because I just realized we never released anything after 3.0.0 according to npm.
2. Creates a publish.md to outline how to release to npm. This no longer requires write access to master to release.

Update changelog and create publish.md

---

package.json

closes #170 
tested with `create-react-app`, `react@17.0.1`, node `v14.15.4` (stable) and npm `v6.14.10` (stable)

Allow React 17 peer dependency

---

package.json
yarn.lock

The latest version of `react-plaid-link` throws an error `Error loading Plaid null` if the plaid script hasn't been initiated on time. 
The reason for it is that `react-script-hook@1.3.0` has a race condition when `checkForExisting` is set to `true`. 
Fortunately, the race condition has been fixed in `1.5.0` - commit: https://github.com/hupe1980/react-script-hook/commit/167085c6db62074f6f57d4271cd5c2a1b9a84e79
This PR should resolve this issue: https://github.com/plaid/react-plaid-link/issues/121

fix(deps): bump react-script-hook to fix `Error loading plaid` msg

---

src/usePlaidLink.ts

in 3.3.0 we inadvertently shipped a bug that broke integrations using a deprecated publicKey configuration along with the `usePlaidLink` hook. This was flagged in #239
This PR restores functionality of public keys by allowing the hook to load as long as 1 of `token` OR `publicKey` is set.
Tests for publicKey are added in #246

(legacy) add support for deprecated publicKey config

---

package.json

this merges #250 into a plaid-owned branch so it can be built and merged

chore: Allow React 18 in `peerDependencies`

---

.github/workflows/build.yml

- The Build action has been broken https://github.com/plaid/react-plaid-link/actions/runs/4024083786/jobs/6915701019
- This bumps this dependency which fixes the issue https://github.com/Borales/actions-yarn/pull/45

Update actions dependency

---

src/factory.ts

Closes #313 
Returning type `Function` is [bad practice for type safety](https://typescript-eslint.io/rules/ban-types/).
This PR refactors the return types of `usePlaidLink` to explicitly state the functions inputs, and return types for better type saftey.
I left `Function` as a type for backwards compatibility.

fix: update function return types to not only return type 'Function'

---

.storybook/example.stories.js
src/PlaidEmbeddedLink.tsx
src/constants.ts
src/index.ts
src/types/index.ts
src/usePlaidLink.ts
src/web3/useEthereumProvider.ts
stories/embedded_link.tsx

- Add `<PlaidEmbeddedLink />` to support embedded Link in the React SDK
- Add embedded Link to storybook
This feature is an unreleased experimental feature that can be enabled for customers on a case-by-case basis. Contact your Account Manager to learn more.
Usage: 
```
const config = {
token: "link-token-123",
onSuccess,
onEvent,
onExit,
};
return (
<PlaidEmbeddedLink
{...config}
style={{
height: '350px',
width: '350px',
}}
/>
);
```

Support embedded Link in Plaid React web SDK

---

PUBLISH.md

- Clarifies that manual publish steps using `npm` only work if the package has already been built via `make`

Update PUBLISH.md to clarify build steps

---

src/PlaidEmbeddedLink.test.tsx
src/PlaidEmbeddedLink.tsx
src/types/index.ts

When the parent component of PlaidEmbeddedLink rerenderers, the component ends up unmounting and invoking createEmbedded again, causing the iframe to reload.
The fix is to stabilize the config object with useMemo if the component props didn't change.
Added unit tests to validate the fix

Prevent unnecessary rerenders for PlaidEmbeddedLink

---

Makefile
package.json
patches/react-script-hook+1.6.0.patch
yarn.lock

If the script can get into a bad state, we err on re-requesting it the next time
(versus https://github.com/plaid/react-plaid-link/pull/351 which keeps the script in the DOM, but may have an even more slight edge case where the script is still not loaded but we don't get a callback)
Tested this with release 3.6.0-beta.1 and it works

Different attempt to fix #285

---

src/react-script-hook/index.test.tsx
src/react-script-hook/index.tsx

- This closes #374 
- I added a unit test for this behavior (now that this logic is no longer done via patch-package), but the unit test would _also_ not have caught this behavior because `exports` / `exports.scripts` is actually defined in the NodeJS runtime (which is also why this didn't get caught by TypeScript)
- ~I am looking into why the Storybooks didn't catch this / surface this~
- Ah right, the storybooks aren't setup to hit this exact case (unmounting while the script is still loading)
- Will release this as 4.0.1

Fix undefined exports issue
