plaid/react-plaid-link

- src/PlaidLink.js
- use actual link to initializer
- change spread props to used props
- fix name of styles prop to butoonStyles
> Some updates:

- src/PlaidLink.js
See https://plaid.com/docs/quickstart/#exit-function
> Add an exit() function

- README.md
Current link goes to a 404 page
> Update plaid link url in README

- src/PlaidLink.js
Plaid has just implemented a new liabilities product and endpoint. See https://blog.plaid.com/liabilities/ for more information.
> Add new liabilities product

- README.md
https://github.com/plaid/react-plaid-link/pull/72#issuecomment-582122347
> Update README.md: s/key/publicKey

- src/PlaidLink.js
Adds `linkCustomizationName` as a prop to the component.
> Add support for linkCustomizationName

- .babelrc
- package.json
- src/PlaidLink.tsx
- src/types/index.ts
- yarn.lock
Fixed https://github.com/plaid/react-plaid-link/issues/84
> Fix proptypes and compile automagically

- README.md
- src/types/index.ts
> Add accountSubtypes as an optional config

- src/usePlaidLink.ts
Reset the component after a product is changed on the config.
> product changes should refresh instance

- src/index.ts
> FIX: Export `PlaidLinkOptions`

- src/usePlaidLink.ts
This PR duplicates this one https://github.com/plaid/react-plaid-link/pull/162
It addresses this issue:
https://github.com/plaid/react-plaid-link/issues/163
> Fix ready state

- README.md
- package.json
- src/factory.ts
- src/index.ts
- src/types/index.ts
- yarn.lock
- Improves readme.md code samples based on feedback in #128 
- Adds TS types for more things
> Improve TS types and examples

- package.json
- yarn.lock
Bumps this repo to use node 14, and upgrades some deps that break in the node 14 upgrade.
> upgade dependencies and node version

- .yarnrc
- yarn.lock
at some point references to artifact.plaid.io got entered into `yarn.lock` file. This does a simple find-and-replace
closes #208
> replace artifact.plaid.io with registry.npmjs.org

- .babelrc
- .github/workflows/build.yml
- Makefile
- jest.config.js
- package.json
- src/usePlaidLink.test.tsx
- stories/hooks.legacy.js
- yarn.lock
- Bumps `react-script-hook` to 1.6 to hopefully solve #239 
- Adds tests to close #29 and reduce future regressions
> Add tests, bump dependencies.

- src/types/web3.ts
https://plaid.com/docs/link/web/#link-web-onsuccess-metadata-wallet
> Add new onSuccess metadata type for wallet name

- src/usePlaidLink.test.tsx
- src/usePlaidLink.ts
also adds/updates tests accordingly
> update early return condition in `usePlaidLink` for possible inputs

- CHANGELOG.md
- package.json
Fixes build issue with version 3.5.0
> release 3.5.1

- README.md
- src/factory.ts
- src/types/index.ts
- src/usePlaidLink.test.tsx
- src/usePlaidLink.ts
In preparation for upcoming products.
> Add support for `handler.submit` API

- CHANGELOG.md
- package.json
> Release 3.6.0

- .npmrc
- CHANGELOG.md
- package.json
Done https://www.npmjs.com/package/react-plaid-link/v/4.0.0
> Release 4.0.0
